### ISSUE TITLE
[JsonSerializer] Nan, Infinity

### ISSUE THREAD

**Issue by pavel-b-novikov** [viknick/nsudotnet#2]
Раз уж вы взялись их обрабатывать, то из каких соображений вы пробрасываете их сразу же в null?

**Comment by viknick** [comment]
С 
"Number: a signed decimal number that may contain a fractional part and may use exponential E notation, but cannot include non-numbers like NaN. "
Вот я решил, раз их нельзя, то пробросил в null

**Comment by viknick** [comment]
"С" это я не дописал, я хотел наеисать "С википедии"

**Comment by pavel-b-novikov** [comment]
![image](https://user-images.githubusercontent.com/2521412/27602332-9fe829b8-5b9c-11e7-9085-14d812a40a5f.png)
Да вроде вполне себе работает

**Comment by viknick** [comment]
У меня же в тестовом примере в Main есть класс с поле Double.Nan, которое в сериализуется в null, и все должно быть верно

**Comment by viknick** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
А, не, я проверил через JSON.parse и вы все-таки правы. Но ладно, оставьте.
