### ISSUE TITLE
[NumberGuesser] Math.Truncate

### ISSUE THREAD

**Issue by pavel-b-novikov** [viknick/nsudotnet#5]
Никто кроме вас двоих не использовал Math.Truncate. На олимпиаде вы тоже скатываете друг у друга?

**Comment by viknick** [comment]
Блин, серьезно? Вот верите нет, я в Академгородке, а Рома в городе, и мы делали отдельно.
У нас из-за олимпиад развилось схожее мышление и нас уже не раз подозревают в списывании.
Я руководствовался тем что надо вывести общее количество минут, оно валяется в TotalMinutes, потом посмотрел увидел что нецелые минуты это плохо, решил что надо целую часть взять. Так и пришел к Math.Truncate. А чем руководствовался Рома, надо у него спросить

**Comment by pavel-b-novikov** [comment]
Ладно, верю
